apiVersion: apps/v1
 # The type of workload we are creating 
kind: Deployment
metadata:
  # Name of deployment - Required
  name: aks-dotnetapp-deployment 
spec:
  replicas: 2
  selector:
    matchLabels: 
      app: aks-dotnetapp
  # Pod template which decribes the pod you want to deploy
  template: 
    metadata:
      # Used to logically group pods together
      labels: 
        app: aks-dotnetapp
    # Specific details about the containers in the Pod
    spec: 
      containers:
      - name: aks-dotnetapp-containers
        # Docker Hub image to use
        image: blesson2001/microservicedemo:latest
        # Define ports to expose
        ports: 
        - containerPort: 80
          # Reference name of port
          name: http 
        resources:
          # Minimum amount of resources we want
          requests: 
            cpu: 100m
            memory: 128Mi
          # Maximum amount of resources we want
          limits: 
            cpu: 250m
            memory: 256Mi

---

apiVersion: v1
 # The type of workload we are creating 
kind: Service
metadata:
# Name of Service - Required
  name: aks-dotnetapp-loadbalancer
# Specific details about the Service
spec:
# Type of Service to be deployed
  type: LoadBalancer
  ports:
  - port: 80
  # Used to tell the Service which Pods to associate with
  selector:
    app: aks-dotnetapp
